version: '3'
services:
  mariadb:
    image: mariadb:10.10
    container_name: mariadb
    environment:
      - MYSQL_DATABASE=capstone
      - MYSQL_ROOT_PASSWORD=Ad13sf46!!
      - MYSQL_USER=root
    ports:
      - "3307:3306"
    networks:
      - cs-essence

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - cs-essence

  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      - cs-essence
    depends_on:
      - mariadb
      - redis

networks:
  cs-essence:
    driver: bridge